name: Pull and Push Docker Image

on:
  push:
    branches:
      - build-argocd  # 可以根据需要修改为其他分支

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Pull Docker image from Quay.io
        run: docker pull quay.io/argoproj/argocd:v2.14.2

      - name: Login to Alibaba Cloud Container Registry
        uses: docker/login-action@v2
        with:
          registry: registry.cn-beijing.aliyuncs.com
          username: ${{ secrets.ALIYUN_REGISTRY_USERNAME }}
          password: ${{ secrets.ALIYUN_REGISTRY_PASSWORD }}

      - name: Tag Docker image
        run: docker tag quay.io/argoproj/argocd:v2.14.2 registry.cn-beijing.aliyuncs.com/tanliyuan/argocd:v2.14.2

      - name: Push Docker image to Alibaba Cloud Container Registry
        run: docker push registry.cn-beijing.aliyuncs.com/tanliyuan/argocd:v2.14.2
