name: Pull and Push Docker Image

on:
  push:
    branches:
      - build-harbor-core  # 可以根据需要修改为其他分支

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Pull Docker image from ghcr.io
        run: docker pull goharbor/harbor-core:v2.12.2

      - name: Login to Alibaba Cloud Container Registry
        uses: docker/login-action@v2
        with:
          registry: registry.cn-beijing.aliyuncs.com
          username: ${{ secrets.ALIYUN_REGISTRY_USERNAME }}
          password: ${{ secrets.ALIYUN_REGISTRY_PASSWORD }}

      - name: Tag Docker image
        run: docker tag goharbor/harbor-core:v2.12.2 registry.cn-beijing.aliyuncs.com/tanliyuan/harbor-core:v2.12.2

      - name: Push Docker image to Alibaba Cloud Container Registry
        run: docker push registry.cn-beijing.aliyuncs.com/tanliyuan/harbor-core:v2.12.2
